Repository AT-PHPIntership/product-tiki, pull requests merged in 2018-05, with the labels that each got.

#4 define route, admin homepage, update bower dependencies
  .bowerrc
  app/Http/Controllers/Admin/HomeController.php
  bower.json
  public/images/favicon.ico
  public/images/img.jpg
  resources/lang/en/messages.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/index.blade.php
  routes/web.php
  tests/Browser/ExampleTest.php
  tests/Feature/ExampleTest.php
Labels: in-review, task, week1

#5 upload migration file
  app/User.php
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2014_10_12_100000_create_password_resets_table.php
  database/migrations/2018_05_10_080438_create_categories_table.php
  database/migrations/2018_05_10_082141_create_products_table.php
  database/migrations/2018_05_10_083515_create_orders_table.php
  database/migrations/2018_05_10_083714_create_images_table.php
  database/migrations/2018_05_10_084045_create_orderdetails_table.php
  database/migrations/2018_05_10_084833_create_posts_table.php
  database/migrations/2018_05_10_085228_create_comments_table.php
  database/migrations/2018_05_10_085527_create_userinfo_table.php
Labels: database, in-review, task, week1

#6 upload model file
  app/Models/Category.php
  app/Models/Comment.php
  app/Models/Image.php
  app/Models/Order.php
  app/Models/OrderDetail.php
  app/Models/Post.php
  app/Models/Product.php
  app/Models/User.php
  app/Models/UserInfo.php
Labels: in-review, task, week1

#8 [Admin] List post
  app/Http/Controllers/Admin/PostController.php
  public/css/post-list.css
  resources/lang/en/messages.php
  resources/lang/en/post.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/posts/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#10 [Admin] Add list product layout
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week1

#15 Admin layout users
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/users/index.blade.php
  resources/views/admin/pages/users/show.blade.php
Labels: in-review, task, week1

#11 Factory and seeder, Minor migration change
  app/Models/Post.php
  app/Models/Product.php
  database/factories/CategoryFactory.php
  database/factories/PostFactory.php
  database/factories/ProductFactory.php
  database/factories/UserFactory.php
  database/migrations/2018_05_10_082141_create_products_table.php
  database/seeds/CategoriesTableSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/PostsTableSeeder.php
  database/seeds/ProductsTableSeeder.php
  database/seeds/UsersTableSeeder.php
Labels: database, in-review, task, week1

#13 [Admin] Get products, show prodcuts, add paginate
  app/Http/Controllers/Admin/ProductController.php
  config/define.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week1

#14 [Admin] Post - List show data
  app/Http/Controllers/Admin/PostController.php
  config/define.php
  resources/lang/en/common.php
  resources/lang/en/post.php
  resources/views/admin/pages/posts/index.blade.php
Labels: in-review, task, week1

#17 [Admin] Create product layout
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/common.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/create.blade.php
Labels: in-review, task, week1

#21 [Admin] Add create product, upload product image
  .gitignore
  app/Http/Controllers/Admin/ProductController.php
  config/define.php
  resources/lang/en/messages.php
  resources/views/admin/layout/message.blade.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week1

#20 Admin list and show user
  app/Http/Controllers/Admin/UserController.php
  app/Models/UserInfo.php
  config/define.php
  database/factories/UserInfoFactory.php
  database/seeds/DatabaseSeeder.php
  database/seeds/UserInfoTableSeeder.php
  resources/lang/en/user.php
  resources/views/admin/pages/users/index.blade.php
  resources/views/admin/pages/users/show.blade.php
Labels: in-review, task, week1

#29 [Admin] Post - Show all comments
  app/Http/Controllers/Admin/PostController.php
  resources/lang/en/post.php
  resources/views/admin/pages/posts/index.blade.php
  resources/views/admin/pages/posts/show.blade.php
Labels: in-review, task, week1

#43 [Admin] Fix post.js for update post status
  public/js/post.js
Labels: in-review, week2

#49 [Admin] Add factory and seeder for order and order_details
  database/factories/OrderDetailFactory.php
  database/factories/OrderFactory.php
  database/seeds/DatabaseSeeder.php
  database/seeds/OrderDetailsTableSeeder.php
  database/seeds/OrdersTableSeeder.php
Labels: in-review, task, week2

#23 [Admin] Post list test
  tests/Browser/AdminPostTest/AdminListPostTest.php
  tests/DuskTestCase.php
Labels: in-review, task, week1

#22 [Admin] Add validation create product
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/PostProductRequest.php
  resources/views/admin/layout/errors.blade.php
  resources/views/admin/pages/products/create.blade.php
Labels: in-review, task, week1

#25 [Admin ] List product test
  tests/Browser/ProductTest/ListProductTest.php
Labels: in-review, task, week1

#31 [admin] delete product
  app/Http/Controllers/Admin/ProductController.php
  app/Models/Product.php
  public/js/product.js
  resources/lang/en/messages.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week1

#19 Create category
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Backend/CategoryRequests.php
  resources/lang/en/category.php
  resources/views/admin/pages/categories/create.blade.php
  resources/views/admin/pages/categories/index.blade.php
Labels: in-review, task, week1

#30 [Admin] Add update product layout, get product info, show product
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/edit.blade.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week1

#32 [Admin] Post Approved, Delete test
  app/Http/Controllers/Admin/PostController.php
  resources/views/admin/pages/posts/index.blade.php
  resources/views/admin/pages/posts/show.blade.php
  tests/Browser/AdminPostTest/AdminListPostTest.php
  tests/Browser/AdminPostTest/AdminPostStatusTest.php
Labels: in-review, task, week1

#50 [Admin] Show all orders & search by status & order by total
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Order.php
  config/define.php
  resources/lang/en/messages.php
  resources/lang/en/orders.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/orders/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#26 [Admin] Test list category
  tests/Browser/ListCategoryTest.php
Labels: in-review, task, week1

#33 [Admin] create product unit test
  tests/Browser/ProductTest/CreateProductTest.php
  tests/Browser/ProductTest/testing/iphone1.jpg
  tests/Browser/ProductTest/testing/iphone1.zip
Labels: in-review, task, week1

#54 Show parent category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
  public/css/show.css
  resources/lang/en/category.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/show.blade.php
Labels: in-review, task, week2

#36 [Admin] Delete subcomments
  app/Http/Controllers/Admin/PostController.php
  app/Http/Controllers/Api/CommentController.php
  app/Models/Comment.php
  public/js/messages.js
  public/js/post.js
  resources/lang/en/post.php
  resources/views/admin/pages/posts/index.blade.php
  resources/views/admin/pages/posts/show.blade.php
  routes/api.php
  routes/web.php
Labels: in-review, task, week2

#53 [Admin] Approve & Delete orders
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Api/OrderController.php
  app/Models/Order.php
  app/Models/OrderDetail.php
  public/js/messages.js
  public/js/order.js
  resources/lang/en/orders.php
  resources/views/admin/pages/orders/index.blade.php
  routes/api.php
Labels: in-review, task, week2

#55 [Admin] Show order details
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Image.php
  config/define.php
  resources/lang/en/orders.php
  resources/views/admin/pages/orders/index.blade.php
  resources/views/admin/pages/orders/show.blade.php
Labels: in-review, task, week2

#46 [admin] Update product, upload multi image, delete image
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Api/ImageController.php
  public/css/product-admin.css
  public/js/messages.js
  public/js/product.js
  resources/lang/en/messages.php
  resources/lang/en/product.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/products/edit.blade.php
  resources/views/admin/pages/products/index.blade.php
  routes/api.php
Labels: in-review, task, week2

#56 [admin] Find product
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week2

#47 [admin] Update product validation
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/UpdateProductRequest.php
  resources/views/admin/pages/products/edit.blade.php
Labels: in-review, task, week2

#58 [Admin] Layout statistic homepage
  resources/lang/en/homepage.php
  resources/views/admin/pages/index.blade.php
Labels: in-review, task, week2

#57 [Admin] Seeder And factory
  database/factories/ImageFactory.php
  database/factories/PostFactory.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ImagesTableSeeder.php
  database/seeds/PostsTableSeeder.php
Labels: in-review, task, week2

#65 fix create category with level column in DB
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Backend/CategoryRequests.php
  app/Models/Category.php
  resources/views/admin/pages/categories/create.blade.php
Labels: in-review, week3

#41 Unittest list user
  resources/lang/en/user.php
  tests/Browser/Pages/Users/ShowListUserTest.php
Labels: in-review, task, week2

#59 Admin send mail create user
  app/Http/Controllers/Admin/UserController.php
  app/Mail/SendMailUser.php
  composer.lock
  config/mail.php
  resources/views/admin/pages/users/index.blade.php
  resources/views/admin/pages/users/mail.blade.php
Labels: in-review, task, week2

#38 Update category
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Backend/EditCategoryRequest.php
  resources/lang/en/category.php
  resources/views/admin/pages/categories/create.blade.php
  resources/views/admin/pages/categories/edit.blade.php
  resources/views/admin/pages/categories/index.blade.php
  routes/web.php
Labels: in-review, task, week3

#39 Delete category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
  public/js/category.js
  public/js/messages.js
  resources/lang/en/category.php
  resources/views/admin/pages/categories/index.blade.php
Labels: in-review, task, week2

#61 Admin get update user
  app/Http/Controllers/Admin/UserController.php
  public/images/img.jpg
  resources/views/admin/pages/users/edit.blade.php
  routes/web.php
Labels: in-review, task, week3

#60 [Admin] unit test for delete product
  resources/views/admin/pages/products/index.blade.php
  tests/Browser/ProductTest/DeleteProductTest.php
  tests/Browser/ProductTest/ListProductTest.php
Labels: in-review, task

#40 [Admin] Comment function test
  app/Http/Controllers/Admin/PostController.php
  resources/views/admin/pages/posts/show.blade.php
  tests/Browser/AdminPostTest/AdminCommentTest.php
Labels: in-review, task, week2

#66 Find product test
  tests/Browser/ProductTest/ListProductTest.php
Labels: in-review, task, week3

#62 [Admin] unit test for update product
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Api/ImageController.php
  public/js/product.js
  resources/lang/en/product.php
  tests/Browser/ProductTest/UpdateProductTest.php
Labels: in-review, task, week3

#74 Admin validate and update user
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  resources/lang/en/messages.php
  resources/views/admin/pages/users/edit.blade.php
Labels: in-review, task, week3
