Repository AT-PHPIntership/product-tiki, pull requests merged in 2018-07, with the labels that each got.

#198 [Api] create comment
  app/Http/Controllers/Api/User/CommentController.php
  app/Http/Requests/CreateCommentsRequest.php
  routes/api.php
Labels: in-review, task, week 6

#220 test api update comment
  tests/Feature/Api/UpdateCommentTest.php
Labels: in-review, task

#228 Use api delete comment
  public/js/public/posts.js
Labels: in-review, task

#225 fix create and update product
  public/js/admin/product.js
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/edit.blade.php
  tests/Browser/Admin/Product/CreateProductTest.php
  tests/Browser/Admin/Product/UpdateProductTest.php
Labels: bug, in-review

#221 test api delete comment
  tests/Feature/Api/DeleteCommentTest.php
Labels: in-review, task

#230 Show api update comments
  app/Http/Controllers/Api/User/CommentController.php
  app/Http/Requests/UpdateCommentRequest.php
  public/js/public/posts.js
Labels: in-review, task

#233 test api create order
  tests/Feature/Api/CreateOrderTest.php
Labels: in-review, task

#234 admin-send-mail-change-status
  app/Http/Controllers/Api/Admin/OrderController.php
  app/Mail/UpdateStatusOrderMail.php
  resources/lang/en/user/mail.php
  resources/views/admin/pages/orders/statusmail.blade.php
  tests/Browser/Admin/Order/OrderListTest.php
Labels: in-review, task

#209 Cancel order
  public/css/public/custom.css
  public/js/messages.js
  public/js/public/userOrder.js
  resources/lang/en/common.php
  resources/lang/en/user/profile.php
  resources/views/public/pages/profile.blade.php
Labels: in-review, task

#203 Submit subcomment
  public/js/messages.js
  public/js/public/posts.js
Labels: in-review, task

#231 [Test] submit comments
  tests/Feature/Api/CreateCommentTest.php
Labels: in-review, task

#235 fix show detail product has preview
  public/css/public/custom.css
  public/js/public/details.js
  resources/lang/en/user/product.php
  resources/views/public/pages/detail.blade.php
Labels: bug, in-review

#238 create table address user
  app/Models/AddressUser.php
  app/Models/UserInfo.php
  database/factories/AddressUserFactory.php
  database/migrations/2018_07_04_042627_create_address_user.php
  database/seeds/AddressUserTableSeeder.php
  database/seeds/DatabaseSeeder.php
Labels: in-review, task

#201 [User] Submit cart
  public/js/messages.js
  public/js/public/details.js
  public/js/public/masterpage.js
  public/js/public/minicart.js
  resources/lang/en/user/cart.php
Labels: in-review, task, week 6

#227 Delete post
  public/js/public/posts.js
Labels: in-review, task

#236 fix layout show order detail
  app/Http/Controllers/Admin/OrderController.php
  public/js/admin/order.js
  resources/lang/en/orders.php
  resources/views/admin/pages/orders/show.blade.php
  tests/Browser/Admin/Order/OrderListTest.php
Labels: bug, in-review

#239 fix databse (create table social network) login facebook
  app/Models/SocialNetwork.php
  app/Models/User.php
  database/migrations/2018_07_04_101953_create_social_networks.php
  database/migrations/2018_07_06_022217_edit_table_user.php
Labels: in-review, task

#244 doc api reset password
  docs/api-references/resetpass.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task

#202 [User] Update order
  public/js/public/userOrder.js
Labels: in-review, task, week 6

#242 [Database&Model] add migration and model for meta table
  app/Models/Meta.php
  app/Models/MetaData.php
  app/Models/Product.php
  database/migrations/2018_07_05_064408_create_meta_table.php
  database/migrations/2018_07_05_064921_create_meta_data_table.php
Labels: database, task

#240 [Test] Update order test
  tests/Feature/Api/UpdateOrderTest.php
Labels: in-review, task

#237 [User] Add trans for vi
  app/Http/Controllers/Controller.php
  app/Http/Kernel.php
  app/Http/Middleware/Language.php
  public/js/messages.js
  public/js/public/main.js
  resources/lang/en/user/locale.php
  resources/lang/vi/user/detail_product.php
  resources/lang/vi/user/index.php
  resources/lang/vi/user/layout.php
  resources/lang/vi/user/login.php
  resources/lang/vi/user/master.php
  resources/lang/vi/user/product.php
  resources/lang/vi/user/profile.php
  resources/lang/vi/user/register.php
  resources/views/public/layout/master.blade.php
  routes/web.php
Labels: in-review, task

#249 [Doc] Api doc get address list
  docs/api-references/profile.md
Labels: in-review, task

#250 [Api] Get list address of user
  app/Http/Controllers/Api/User/UserInfoController.php
  routes/api.php
Labels: in-review, task

#253 [Doc] Api doc compare product
  docs/api-references/product.md
Labels: in-review, task

#255 [Fix] Update order, message submit order
  public/js/public/masterpage.js
  public/js/public/userOrder.js
Labels: bug

#251 [Api & User] Show list address user and Edit Address
  app/Http/Controllers/Api/User/UserInfoController.php
  public/css/public/profile.css
  public/js/messages.js
  public/js/public/userProfile.js
  resources/lang/en/user/profile.php
  resources/views/public/pages/profile.blade.php
  routes/api.php
Labels: in-review, task

#241 Layout login facebook
  public/css/public/custom.css
  resources/lang/en/user/login.php
  resources/views/public/pages/login.blade.php
Labels: in-review, task

#142 [Test] Get comments
  tests/Feature/Api/CommentApiTest.php
Labels: in-review, task, week 5

#211 [Test] Get posts
  tests/Feature/Api/PostApiTest.php
Labels: in-review, task

#245 [Database] password_resets table
  database/migrations/2018_07_03_080517_create_password_resets_table.php
Labels: database, in-review, task

#252 [Admin] Add or edit meta for product
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/UpdateMetaRequest.php
  public/js/admin/product.js
  resources/lang/en/product.php
  resources/views/admin/pages/products/edit.blade.php
  resources/views/admin/pages/products/editMeta.blade.php
  resources/views/admin/pages/products/index.blade.php
  routes/web.php
Labels: in-review, task

#259 layout recommend product
  public/css/public/custom.css
  public/css/public/owl.carousel.css
  public/js/public/details.js
  public/js/public/owl.carousel.js
  resources/lang/en/user/detail_product.php
  resources/views/public/pages/detail.blade.php
Labels: in-review, task

#247 [Api] reset password
  app/Http/Controllers/Api/User/ForgotPasswordController.php
  app/Http/Controllers/Api/User/ResetPasswordController.php
  routes/api.php
Labels: in-review, task

#256 doc api get list recommend product
  docs/api-references/product.md
Labels: in-review, task

#262 [Use] Compare products
  public/css/public/custom.css
  public/css/public/style.css
  public/js/public/details.js
  resources/lang/en/user/detail_product.php
  resources/views/public/pages/detail.blade.php
Labels: in-review, task

#263 test api reset password
  tests/Feature/Api/ResetPasswordTest.php
Labels: in-review, task

#260 create table time order status
  app/Models/Order.php
  app/Models/TrackingOrder.php
  database/migrations/2018_07_10_072314_create_table_tracking_order.php
Labels: database, in-review, task

#261 create table coupon for order
  app/Models/Coupon.php
  app/Models/Order.php
  database/migrations/2018_07_10_082438_create_table_coupon.php
  database/migrations/2018_07_10_091918_add_column_coupon_id_in_order_table.php
Labels: database, in-review, task

#265 add time when change status order
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Api/User/OrderController.php
  app/Models/TrackingOrder.php
  database/migrations/2018_07_13_024125_modify_tracking_order_table.php
  resources/lang/en/orders.php
Labels: in-review, task

#264 [Database] Add column "address" to orders table
  app/Models/Order.php
  database/migrations/2018_07_12_070733_add_address_to_order_table.php
Labels: database, in-review, task

#277 [Admin]update layout order detail
  public/css/admin/show.css
  resources/lang/en/orders.php
  resources/views/admin/pages/orders/show.blade.php
Labels: bug, in-review

#258 [Api] Get recommend products
  app/Http/Controllers/Api/User/ProductController.php
  routes/api.php
Labels: in-review, task

#270 [Feature] Login facebook
  app/Http/Controllers/Api/User/LoginController.php
  app/Models/User.php
  composer.json
  composer.lock
  config/define.php
  database/migrations/2018_07_16_045058_add_column_social_user_table.php
  public/js/public/login.js
  resources/views/public/pages/login.blade.php
  routes/api.php
Labels: database, in-review, task

#273 [Layout] cart page
  app/Http/Controllers/Home/CartController.php
  public/css/public/custom.css
  public/css/public/style.css
  public/js/public/cart.js
  resources/lang/en/user/cart.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/cart.blade.php
  routes/web.php
Labels: in-review, task
