Repository AT-PHPIntership/product-tiki, pull requests merged in 2018-06, with the labels that each got.

#75 [Admin] Sort product
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week3

#42 Test create categoy
  app/Http/Requests/Backend/CategoryRequest.php
  resources/views/admin/pages/categories/create.blade.php
  tests/Browser/Admin/CreateCategoryTest.php
Labels: in-review, task, week3

#84 fix form update category and validate
  app/Http/Requests/Backend/EditCategoryRequest.php
  resources/views/admin/pages/categories/edit.blade.php
  resources/views/admin/pages/categories/index.blade.php
Labels: in-review, task, week4

#70 [Admin] Add 'note' column for orders table and fix factory
  database/factories/OrderFactory.php
  database/migrations/2018_05_10_083515_create_orders_table.php
Labels: database, in-review, week3

#89 [Admin] Generate admin login form
  app/Http/Controllers/HomeController.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Browser/ExampleTest.php
  tests/Feature/ExampleTest.php
Labels: in-review, task, week4

#68 [Admin] Fix post-details, add feature sort posts, remove feature search by content
  app/Http/Controllers/Admin/PostController.php
  config/define.php
  resources/lang/en/post.php
  resources/views/admin/pages/posts/index.blade.php
  resources/views/admin/pages/posts/show.blade.php
  tests/Browser/AdminPostTest/AdminListPostTest.php
Labels: in-review, task, week3

#90 [Admin] Login feature
  app/Exceptions/Handler.php
  app/Http/Controllers/Auth/LoginController.php
  app/Models/User.php
  config/auth.php
  database/seeds/UsersTableSeeder.php
  resources/views/admin/layout/master.blade.php
  resources/views/auth/login.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: in-review, task, week4

#93 fix can not update category = this child
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Backend/EditCategoryRequest.php
  resources/lang/en/category.php
Labels: in-review, task, week4

#96 edit update user request
  app/Http/Requests/UpdateUserRequest.php
Labels: bug, in-review, week4

#77 [Admin] Change create,update image, change validation create,update product
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Api/ImageController.php
  app/Http/Requests/PostProductRequest.php
  app/Http/Requests/UpdateProductRequest.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/edit.blade.php
  tests/Browser/ProductTest/CreateProductTest.php
Labels: in-review, task, week3

#72 [Admin] Order - List and Details fix
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Api/OrderController.php
  app/Models/Order.php
  config/define.php
  public/js/messages.js
  public/js/order.js
  resources/lang/en/orders.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/orders/index.blade.php
  resources/views/admin/pages/orders/show.blade.php
  routes/api.php
Labels: in-review, task, week3

#98 move file test in tests/Browser/Admin
  tests/Browser/Admin/Category/CreateCategoryTest.php
  tests/Browser/Admin/Category/ListCategoryTest.php
  tests/Browser/Admin/Post/CommentTest.php
  tests/Browser/Admin/Post/ListPostTest.php
  tests/Browser/Admin/Post/PostStatusTest.php
  tests/Browser/Admin/Product/CreateProductTest.php
  tests/Browser/Admin/Product/DeleteProductTest.php
  tests/Browser/Admin/Product/ListProductTest.php
  tests/Browser/Admin/Product/UpdateProductTest.php
  tests/Browser/Admin/Product/testing/iphone1.jpg
  tests/Browser/Admin/Product/testing/iphone1.zip
  tests/Browser/Admin/Users/CreateUserTest.php
  tests/Browser/Admin/Users/ShowListUserTest.php
  tests/Browser/Admin/Users/UpdateUserTest.php
Labels: in-review, week4

#88 test update category
  tests/Browser/Admin/Category/UpdateCategoryTest.php
Labels: in-review, task, week4

#100 [Admin] Save data before update, create
  public/js/messages.js
  public/js/product.js
  resources/lang/en/product.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/edit.blade.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week3

#64 [Admin] homepage statistic
  app/Http/Controllers/Admin/HomeController.php
  app/Http/Controllers/Api/HomeController.php
  config/define.php
  database/seeds/UserInfoTableSeeder.php
  public/css/homepage.css
  public/js/homepage.js
  resources/lang/en/homepage.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/index.blade.php
  routes/api.php
  routes/web.php
Labels: in-review, task

#103 [Admin] Delete product and childs
  app/Http/Controllers/Admin/ProductController.php
  resources/lang/en/messages.php
Labels: in-review, week4

#104 Admin edit function delete
  public/js/category.js
  public/js/main.js
  public/js/messages.js
  public/js/order.js
  public/js/post.js
  public/js/product.js
  resources/lang/en/messages.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/orders/index.blade.php
  resources/views/admin/pages/posts/index.blade.php
  resources/views/admin/pages/products/index.blade.php
  tests/Browser/Admin/Category/DeleteCategoryTest.php
  tests/Browser/Admin/Product/DeleteProductTest.php
Labels: in-review, task, week4

#97 Delete user
  app/Http/Controllers/Admin/UserController.php
  app/Models/User.php
  public/js/main.js
  public/js/messages.js
  resources/lang/en/messages.php
  resources/views/admin/pages/users/index.blade.php
Labels: in-review, task, week4

#107 [Admin] Fix route admin.homepage
  resources/views/admin/pages/index.blade.php
Labels: bug

#105 Admin sort user
  app/Http/Controllers/Admin/UserController.php
  app/Models/User.php
  app/Models/UserInfo.php
  composer.json
  composer.lock
  config/app.php
  config/columnsortable.php
  resources/views/admin/pages/users/index.blade.php
Labels: done-review, task, week4

#76 Fix layout index and show category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
  resources/lang/en/category.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/show.blade.php
  tests/Browser/Admin/Category/DeleteCategoryTest.php
Labels: in-review, task, week3

#108 fix userinfo
  app/Http/Requests/UpdateUserRequest.php
  resources/views/admin/pages/users/edit.blade.php
  resources/views/admin/pages/users/index.blade.php
  resources/views/admin/pages/users/show.blade.php
Labels: bug, task, week4

#110 Category sort by name and sort by products_count
  app/Http/Controllers/Admin/CategoryController.php
  config/define.php
  resources/views/admin/pages/categories/index.blade.php
Labels: in-review, task, week4

#111 fix layout user
  resources/views/admin/pages/users/index.blade.php
Labels: in-review, task, week4

#112 Add css and js, font file public template
  public/css/public/bootstrap.css
  public/css/public/custom.css
  public/css/public/font-awesome.css
  public/css/public/skdslider.css
  public/css/public/style.css
  public/fonts/FontAwesome.otf
  public/fonts/fontawesome-webfont.eot
  public/fonts/fontawesome-webfont.ttf
  public/fonts/fontawesome-webfont.woff
  public/fonts/fontawesome-webfont.woff2
  public/fonts/glyphicons-halflings-regular.eot
  public/fonts/glyphicons-halflings-regular.ttf
  public/fonts/glyphicons-halflings-regular.woff
  public/fonts/glyphicons-halflings-regular.woff2
  public/js/public/bootstrap.min.js
  public/js/public/custom.js
  public/js/public/easing.js
  public/js/public/jquery-1.11.1.min.js
  public/js/public/minicart.min.js
  public/js/public/move-top.js
  public/js/public/responsiveslides.min.js
  public/js/public/skdslider.min.js
Labels: in-review, task, week4

#101 Init Trait ApiResponser
  app/Http/Controllers/Api/Admin/CommentController.php
  app/Http/Controllers/Api/Admin/HomeController.php
  app/Http/Controllers/Api/Admin/ImageController.php
  app/Http/Controllers/Api/Admin/OrderController.php
  app/Http/Controllers/Api/Admin/PostController.php
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/User/ProductController.php
  app/Traits/ApiResponser.php
  routes/api.php
  routes/web.php
Labels: in-review, task, week4

#106 Admin testing delete user
  tests/Browser/Admin/Users/DeleteUserTest.php
Labels: in-review, task, week4

#109 Admin unittest sort user
  resources/views/admin/pages/users/index.blade.php
  tests/Browser/Admin/Users/SortUserTest.php
Labels: in-review, task, week4

#73 Public layout
  app/Http/Controllers/Home/HomeController.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/index.blade.php
  routes/web.php
  tests/Browser/ExampleTest.php
Labels: in-review, task, week3

#114 fix delete category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
Labels: bug, in-review

#117 fix still sort when paginate
  app/Http/Controllers/Admin/CategoryController.php
Labels: bug, in-review, week4

#91 [Admin] Fix index layout product
  public/css/admin/product-admin.css
  resources/lang/en/common.php
  resources/views/admin/pages/products/index.blade.php
Labels: in-review, task, week4

#99 Init api doc
  docs/api-references/api.md
  docs/api-references/category.md
  resources/views/api-doc-builders/index.blade.php
  resources/views/api-docs.blade.php
  routes/web.php
Labels: in-review, week4

#120 fix_path_file
  resources/views/admin/pages/products/index.blade.php
  resources/views/admin/pages/users/index.blade.php
Labels: bug, in-review

#121 Fix relationship category model
  app/Models/Category.php
Labels: bug, in-review

#118 Doc api product
  docs/api-references/product.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week4

#123 fix change to page 2 and click sort
  resources/views/admin/pages/categories/index.blade.php
Labels: bug, in-review

#119 Test sort category
  resources/views/admin/pages/categories/index.blade.php
  tests/Browser/Admin/Category/SortCategoryTest.php
Labels: in-review, task, week4

#124 [Admin] Fix bug sort paginate
  resources/views/admin/pages/products/index.blade.php
Labels: bug, in-review, week4

#92 [Admin] Add middleware for Admin login
  app/Http/Kernel.php
  app/Http/Middleware/Admin.php
  routes/web.php
  tests/Browser/Admin/Category/CreateCategoryTest.php
  tests/Browser/Admin/Category/DeleteCategoryTest.php
  tests/Browser/Admin/Category/ListCategoryTest.php
  tests/Browser/Admin/Category/SortCategoryTest.php
  tests/Browser/Admin/Category/UpdateCategoryTest.php
  tests/Browser/Admin/Post/CommentTest.php
  tests/Browser/Admin/Post/ListPostTest.php
  tests/Browser/Admin/Post/PostStatusTest.php
  tests/Browser/Admin/Product/CreateProductTest.php
  tests/Browser/Admin/Product/DeleteProductTest.php
  tests/Browser/Admin/Product/ListProductTest.php
  tests/Browser/Admin/Product/UpdateProductTest.php
  tests/Browser/Admin/Users/CreateUserTest.php
  tests/Browser/Admin/Users/DeleteUserTest.php
  tests/Browser/Admin/Users/ShowListUserTest.php
  tests/Browser/Admin/Users/SortUserTest.php
  tests/Browser/Admin/Users/UpdateUserTest.php
  tests/Browser/AdminLoginTest.php
  tests/Browser/ExampleTest.php
  tests/DuskTestCase.php
Labels: in-review, task, week4

#116 Api get categories
  app/Http/Controllers/Api/User/CategoryController.php
  app/Models/Category.php
  routes/api.php
Labels: in-review, task, week4

#122 add file image template user and fix path
  .gitignore
  public/images/Example/3.png
  public/images/Example/offer.png
  public/images/banner/b1.jpg
  public/images/banner/b3.jpg
  public/images/icon/arrow.png
  public/images/icon/check.png
  public/images/icon/close_1.png
  public/images/icon/icon1.png
  public/images/icon/icon2.png
  public/images/icon/star.png
  public/images/icon/star1.png
  public/images/icon/tick.png
  resources/views/public/pages/index.blade.php
Labels: in-review, task, week4

#132 add bootstrap package template user
  resources/views/public/layout/master.blade.php
Labels: bug, in-review

#130 fix doc api product
  docs/api-references/product.md
Labels: in-review, task, week 5

#133 fix api for category
  app/Http/Controllers/Api/User/CategoryController.php
Labels: in-review, task, week 5

#129 Show api category user
  public/js/public/category.js
  resources/views/public/layout/master.blade.php
Labels: in-review, task, week 5

#126 Api doc for get posts
  docs/api-references/post.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 5

#82 [Admin] Sort Post Test
  resources/views/admin/pages/posts/index.blade.php
  tests/Browser/Admin/Post/AdminSortPostTest.php
Labels: in-review, task, week4

#128 [Api] Get Comments of Post
  app/Http/Controllers/Api/User/CommentController.php
  routes/api.php
Labels: in-review, task

#134 [User] Layout Login
  app/Http/Controllers/Home/LoginController.php
  resources/lang/en/user/layout.php
  resources/lang/en/user/login.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/login.blade.php
  routes/web.php
Labels: in-review, task, week 5

#125 docs api get detail product
  docs/api-references/detail_product.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week4

#136 [Api] Login Feature
  app/Http/Controllers/Api/User/LoginController.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  app/Traits/ApiResponser.php
  composer.json
  composer.lock
  config/auth.php
  config/define.php
  routes/api.php
Labels: in-review, task, week 5

#135 add product and detail page
  app/Http/Controllers/Home/ProductController.php
  public/css/public/custom.css
  public/css/public/font-awesome.css
  resources/lang/en/user/master.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/detail.blade.php
  resources/views/public/pages/index.blade.php
  resources/views/public/pages/products.blade.php
  routes/web.php
Labels: in-review, task, week 5

#138 User api post
  app/Http/Controllers/Api/User/ProductController.php
  resources/lang/en/user/login.php
  routes/api.php
Labels: in-review, task, week 5

#145 api-get-orders
  app/Http/Controllers/Api/User/OrderController.php
  routes/api.php
Labels: in-review, task, week 5

#148 update doc api get detail product
  docs/api-references/detail_product.md
Labels: bug, in-review

#140 doc order
  docs/api-references/order.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 5

#151 update define api post
  app/Http/Controllers/Api/User/ProductController.php
Labels: bug, in-review, week 5

#115 [Admin] Sort product test
  resources/views/admin/pages/products/index.blade.php
  tests/Browser/Admin/Product/ListProductTest.php
Labels: in-review, task, week4

#137 Fix doc get posts
  docs/api-references/post.md
Labels: in-review, task, week 5

#149 Define api detail product
  app/Http/Controllers/Api/User/ProductController.php
Labels: in-review, task, week 5

#143 [User] Register
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/User/LoginController.php
  app/Http/Requests/CreateUserRequest.php
Labels: in-review, task, week 5

#150 [User] Add link for category
  public/js/public/category.js
  public/js/public/route.js
  resources/views/public/layout/master.blade.php
Labels: in-review, task, week 5

#146 [Api] Doc for Login, logout, register
  docs/api-references/user.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 5

#157 edit define api post 2
  app/Http/Controllers/Api/User/ProductController.php
Labels: bug, in-review, week 5

#155 use api show posts for detail product
  public/css/public/custom.css
  public/js/messages.js
  public/js/public/posts.js
  resources/lang/en/user/detail_product.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/detail.blade.php
Labels: in-review, task, week 5

#159 unitest api detail product
  tests/Feature/Api/DetailProductTest.php
Labels: in-review, task, week 5

#164 update paginate api get orders
  app/Http/Controllers/Api/User/OrderController.php
Labels: bug, in-review

#81 Admin button delete avatar user
  app/Http/Controllers/Admin/UserController.php
  public/js/admin/deleteAvatar.js
  resources/views/admin/layout/master.blade.php
  resources/views/admin/pages/users/edit.blade.php
  routes/web.php
Labels: in-review, task, week3

#162 Modify product table
  app/Models/Product.php
  database/factories/OrderDetailFactory.php
  database/migrations/2018_06_15_040218_modify_products_table.php
Labels: database, in-review, week 5

#161 doc api profile user
  docs/api-references/profile.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 5

#167 fix api show posts
  public/css/public/custom.css
  public/js/public/posts.js
Labels: bug, in-review

#131 Api for get product
  app/Http/Controllers/Api/User/ProductController.php
  app/Models/Product.php
  app/Traits/ApiResponser.php
  app/Traits/FilterTrait.php
  config/define.php
Labels: in-review, task, week 5

#160 [User] Profile layout
  app/Http/Controllers/Home/UserController.php
  public/css/public/profile.css
  resources/lang/en/user/profile.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/profile.blade.php
  routes/web.php
Labels: in-review, task, week 5

#154 [Api] Get Posts of user
  app/Http/Controllers/Api/User/PostController.php
  routes/api.php
Labels: in-review, task, week 5

#153 [Api] Doc get posts of logged in user
  docs/api-references/post.md
Labels: in-review, task, week 5

#127 Api doc for get comments
  docs/api-references/comment.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 5

#168 Update api doc get posts
  docs/api-references/post.md
Labels: in-review, week 5

#152 Use api to login, logout
  app/Http/Controllers/Api/User/LoginController.php
  public/js/public/login.js
  public/js/public/masterpage.js
  resources/lang/en/user/layout.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/login.blade.php
  routes/api.php
Labels: in-review, task, week 5

#156 [Api] Create posts
  app/Http/Controllers/Api/User/PostController.php
  app/Http/Requests/CreatePostRequest.php
  routes/api.php
Labels: in-review, task, week 5

#171 [User] Filter products
  app/Http/Controllers/Api/User/ProductController.php
  app/Traits/FilterTrait.php
  public/css/public/custom.css
  public/css/public/style.css
  public/js/public/category.js
  public/js/public/details.js
  public/js/public/master.js
  public/js/public/product.js
  public/js/public/route.js
  resources/lang/en/user/layout.php
  resources/lang/en/user/product.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/detail.blade.php
  resources/views/public/pages/products.blade.php
Labels: in-review, task

#158 Use api register
  public/js/public/register.js
  resources/views/public/pages/register.blade.php
Labels: in-review, task, week 5

#170 Testing api for product
  docs/api-references/product.md
  tests/Feature/Api/apiProductTest.php
Labels: in-review, task, week 5

#172 Layout edit profile
  resources/lang/en/user/profile.php
  resources/lang/en/user/register.php
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#182 [Test] Fix product Api test
  tests/Feature/Api/apiProductTest.php
Labels: bug, week 6

#144 Use api get products index page
  public/css/public/style.css
  public/images/Example/new.png
  public/js/messages.js
  public/js/public/main.js
  resources/lang/en/user/index.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/detail.blade.php
  resources/views/public/pages/index.blade.php
Labels: in-review, task, week 5

#166 doc-api-update-and-delete-post
  docs/api-references/post.md
Labels: in-review, task, week 5

#174 doc api update and delete comments
  docs/api-references/comment.md
Labels: in-review, task, week 6

#181 doc api detail order
  docs/api-references/detail_order.md
  resources/views/api-doc-builders/index.blade.php
Labels: in-review, task, week 6

#176 Show api profile post and subcomment
  app/Http/Controllers/Api/User/PostController.php
  public/css/public/profile.css
  public/js/public/profile.js
  public/js/public/userposts.js
  resources/lang/en/user/profile.php
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#188 api get order detail
  app/Http/Controllers/Api/User/OrderController.php
Labels: in-review, task, week 6

#185 [Api] edit user profile
  app/Http/Controllers/Api/User/UserInfoController.php
  app/Http/Requests/UpdateUserRequest.php
  routes/api.php
Labels: in-review, task, week 6

#183 Submit create post
  public/css/public/style.css
  public/js/public/posts.js
  resources/lang/en/user/detail_product.php
  resources/views/public/pages/detail.blade.php
Labels: in-review, task, week 6

#173 Show user profile
  public/js/public/masterpage.js
  public/js/public/userProfile.js
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#189 test api get profile user
  tests/Feature/Api/ProfileUserTest.php
Labels: in-review, task, week 6

#190 add request perpage for paginate orders
  app/Http/Controllers/Api/User/OrderController.php
Labels: bug, in-review

#180 [Test] get posts of user
  tests/Feature/Api/GetProfilePostsTest.php
  tests/Feature/ExampleTest.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
Labels: in-review, task, week 6

#187 Layout cart
  public/css/public/custom.css
  public/js/public/minicart.js
  resources/views/public/layout/master.blade.php
Labels: in-review, task, week 6

#186 [Doc] api create order
  docs/api-references/order.md
Labels: in-review, task, week 6

#192 Show user order
  public/js/public/userOrder.js
  resources/lang/en/user/profile.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#191 [Api] Calculate avg-rating of product when approve review
  app/Http/Controllers/Api/Admin/PostController.php
  resources/views/admin/pages/posts/index.blade.php
Labels: in-review, task, week 6

#204 edit css subcomment of profileuser
  public/js/public/userposts.js
  resources/lang/en/user/profile.php
  resources/views/public/pages/profile.blade.php
Labels: bug, in-review, week 6

#207 api update status order
  app/Http/Controllers/Api/User/OrderController.php
  config/define.php
  routes/api.php
Labels: in-review, task, week 6

#208 define update and delete post
  app/Http/Controllers/Api/User/PostController.php
  app/Http/Requests/UpdatePostRequest.php
Labels: in-review, task, week 6

#213 Test api edit profile
  tests/Feature/Api/EditProfileTest.php
Labels: in-review, task, week 6

#205 Testing api order of user
  docs/api-references/order.md
  tests/Feature/Api/apiProfileOrderTest.php
Labels: in-review, task, week 6

#175 [Test] Authenticate Test
  tests/Feature/Api/LoginTest.php
  tests/Feature/Api/RegisterTest.php
Labels: in-review, task, week 6

#197 [Doc] create comment
  docs/api-references/comment.md
Labels: in-review, task, week 6

#212 doc cancel order
  docs/api-references/order.md
Labels: in-review, task, week 6

#210 Testing order detail
  public/images/Example/3.png
  tests/Feature/Api/detailOrderTest.php
Labels: in-review, task, week 6

#195 Edit user profile
  public/js/public/userProfile.js
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#206 [Admin] Fix layout edit, create products
  resources/lang/en/common.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/edit.blade.php
Labels: bug, in-review

#200 Show order detail
  public/js/public/userOrder.js
  resources/views/public/pages/profile.blade.php
Labels: in-review, task, week 6

#215 fix filter post and rating
  app/Http/Controllers/Api/User/ProductController.php
  public/js/messages.js
  public/js/public/posts.js
  resources/lang/en/user/detail_product.php
  resources/views/public/pages/detail.blade.php
Labels: bug, in-review, week 6

#217 Test api update post
  app/Http/Controllers/Api/User/PostController.php
  tests/Feature/Api/UpdatePostTest.php
Labels: in-review, task

#218 test api delete post
  tests/Feature/Api/DeletePostTest.php
Labels: in-review, task

#224 fix test api cancel order
  app/Models/Order.php
  app/Models/User.php
  tests/Feature/Api/cancelOrderTest.php
Labels: bug, in-review

#194 [Doc] Update Order API
  docs/api-references/order.md
Labels: in-review, task, week 6

#226 Fix layout header masterpage
  public/js/public/masterpage.js
  resources/views/public/layout/master.blade.php
Labels: bug, in-review

#219 Layout edit/delete post, comment
  public/css/public/custom.css
  public/css/public/style.css
  public/js/public/masterpage.js
  public/js/public/posts.js
  resources/views/public/pages/detail.blade.php
Labels: in-review, task

#222 add migrate preview column
  app/Http/Requests/PostProductRequest.php
  app/Models/Product.php
  database/factories/ProductFactory.php
  database/migrations/2018_06_29_085116_add_preview_to_product_table.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/create.blade.php
  tests/Browser/Admin/Product/CreateProductTest.php
Labels: bug, in-review

#223 fix layout show list products
  resources/lang/en/product.php
  resources/views/admin/pages/products/index.blade.php
Labels: bug, in-review

#178 [Test] Create Posts Test
  tests/Feature/Api/CreatePostsTest.php
Labels: in-review, task, week 6

#196 [Api] update and delete comments
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/User/CommentController.php
  app/Http/Requests/UpdateCommentRequest.php
  config/define.php
  routes/api.php
Labels: in-review, task, week 6

#193 [Api] Create order
  app/Http/Controllers/Api/User/OrderController.php
  app/Http/Requests/CreateOrderRequest.php
  config/define.php
Labels: in-review, task, week 6
